name: Rename Folder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: andstor/copycat-action@v3

      - name: Run a one-line script
        run: echo Hello, world!
